version: '3'
services:
    client:
        build: ./client/
        command: 'npm run serve'
        ports: 
            - '8000:8000'
        volumes: 
            - './client:/usr/src/app/client'
    webapi:
        build: ./webapi/
        command: 'npm run start'
        ports: 
            - '8001:8001'
        volumes: 
            - './webapi:/usr/src/app/webapi'
        depends_on: 
            - 'client'